### ISSUE TITLE
Orika how to configure according to the field name global ruled exclude.

### ISSUE THREAD

**Issue by webeasymail** [orika-mapper/orika#112]
Orika how to configure according to the field name global ruled exclude (hope all class exclude filed by name "errors" 、“metaClass” 、 “expandoMetaClass”)

Such as:

```
      mapperFactory.classMap(Product.class, ProductDTO.class).exclude("errors").exclude("metaClass").exclude("expandoMetaClass").byDefault().register()
```

But I need to eliminate all class this a few properties

**Comment by elaatifi** [comment]
Hello,

You can address this concern by setting a new ClassMapBuilderFactory.

You can provide your own newClassMapBuilder method definition to put the common configuration for all objects

There is some example out there on how to customize ClassMapBuilderFactory here is an example that map Java Bean to Mongo DB object by using the same approach.

https://gist.github.com/elaatifi/ade7321a1405c61ff8a9#file-mongomapper-java

Hope this can help you !
