### ISSUE TITLE
ClassLoader strategy coherency

### ISSUE THREAD

**Issue by acourouppe** [orika-mapper/orika#114]
Hi, 

I'm currently trying to use Orika in an OSGI container. I managed to have it working but I had to make an update to Orika source code itself.  

Almost, everywhere in Orika core, the ClassLoader  is retrieved by using `Thread.currentThread().getContextClassLoader()`. 

I can easily get around this by setting the current tread class loader to the bundle one before calling Orika BUT in one location, the classloader is NOT retrieved from the current thread making my trick useless : JavassistCompilerStrategy (line 254) 

`compiledClass = byteCodeClass.toClass(this.getClass().getClassLoader(),this.getClass().getProtectionDomain());`

Changing this class to make it use the same strategy (current thread class loader) as everywhere else would make it possible to use Orika more easily in an OSGI container (at least without having to have your own in-house build)

**Comment by elaatifi** [comment]
Can you please make a pull request ? Thanks !

**Comment by acourouppe** [comment]
Hi, 

Any idea when you could have a look at this and integrate the change? The pull request is available. CI failed but, it seems to me it was already in failure before my change which is very small. Anyway, let me know if I did something wrong. 

Thanks
