### ISSUE TITLE
1.5.0 Final

### ISSUE THREAD

**Issue by dickerpulli** [orika-mapper/orika#117]
Hi.

Is there any plan to release 1.5.0 final version in the next days, week, months?

Beta is out approx. 1 year now.

Regards.
 Thomas Bosch

**Comment by Mario-Eis** [comment]
+1

**Comment by mathieuruellan** [comment]
+1

**Comment by andreabertagnolli** [comment]
@elaatifi there's a roadmap for the next release?
I'm really interested to partecipate in development.

**Comment by elaatifi** [comment]
@andreabertagnolli really glad if you can help.
Take a look at the issues list and drop me a mail (elaatifi at google mail service) so we can have a little chat I would be glad help you work on some of the issues assigned to 1.5.0 release there was already a beta but more issues need to be fixed before final release.

**Comment by brabenetz** [comment]
I would like to add some fixes before the Orika 1.5 release.
On some points the MappingContext get be lost during Mapping (see draft [orika-2016-11-08.txt](https://github.com/orika-mapper/orika/files/611345/orika-2016-11-08.txt)).
I'm currently prepare a UnitTests to cover this changes.

Also #105 should be easy to fix.

**Comment by andreabertagnolli** [comment]
cool! :)

**Comment by andreabertagnolli** [comment]
can we estabilish a deadline date for the release?

**Comment by andreabertagnolli** [comment]
I think we can go with 1.5.0, or do you think that's better release a beta1?

**Comment by elaatifi** [comment]
We can go with 1.5.0

**Comment by andreabertagnolli** [comment]
Released
