### ISSUE TITLE
CustomConverter not called on null values

### ISSUE THREAD

**Issue by roibert** [orika-mapper/orika#126]
Hello everyone

I'm using Orika 1.4.6 and I'd like to use a CustomConverter to map one of my fields. When the source field is null, the converter doesn't seem to be called. Here is my code:

    class From {
        String source;
    }
    
    class To {
        String destination = "defaultValue";
    }
    
    public class Mapper extends ConfigurableMapper {
    
      private class MyConverter extends CustomConverter<String, String> {
    
        @Override
        public String convert(String source, Type<? extends String> destinationType) {
          if (null == source) {
            return "NULL!";
          }
          return "->" + source + "<-";
        }
      }
    
      @Override
      protected void configure(MapperFactory factory) {
    
        factory.getConverterFactory().registerConverter("converter", new MyConverter());
    
        factory.classMap(From.class, To.class)
    
            .fieldMap("source", "destination")
            .mapNulls(true)
            .converter("converter")
            .add()
    
        .register();
      }
    }

If I map the following object:

    From from = new From(); //from.source == null

    Mapper mapper = new Mapper();
    To to = mapper.map(from, To.class);

    System.out.println(to.destination);

I expect the following output:

    NULL!

However I get the following:

    null

which suggests that the converter isn't called at all and the null value is simply copied, because of

    .mapNulls(true)

If I now set

    .mapNulls(false)

the problem remains the same, as the null value in the source field is ignored which leaves the destination field unchanged (in this case with the value "defaultValue").

It would for example be possible to use the "customize" method in combination with a CustomMapper. However this solution is a lot more complex in my real application and therefore the solution with the CustomConverter seems much more appropriate.

Is this behaviour intentional, or is there any other issue with my example?

Cheers, 
Robert

**Comment by elaatifi** [comment]
Actually this is an intentional behavior all converters has been designed so the source is not null, it may be an easy fix, but this will broke contract, and can be a regression for people using it this way.
This is also a semantic issue (at least our initial assumption), since null when converted is null or default value for primitives.

mapNulls(false) was intended to not overwrite destination values when source is null.

for your need it's better to have a custom object factory that instantiate your destination object with your default values and use mapNulls(false)

**Comment by roibert** [comment]
Thank you for the quick answer. The idea with the object factory nicely solves my problem!

**Comment by elaatifi** [comment]
Thanks, glad it solve your issue :)
