### ISSUE TITLE
CodeGenerationStrategy.addSpecification(...) should accept Class<T extends Specification> instead of Class<Specification>

### ISSUE THREAD

**Issue by kalyan01** [orika-mapper/orika#134]
If one wants to to add a custom specification to CodeGenerationStrategy to replace an existing strategy, CodeGenerationStrategy.addSpecification() as follows:

new DefaultMapperFactory.Builder()
            .getCodeGenerationStrategy()
            .addSpecification(new MySpecification(), 
                CodeGenerationStrategy.Position.IN_PLACE_OF,
                ma.glasnost.orika.impl.generator.specification.Convert.class);

However, the 3rd argument is of type Class<ma.glasnost.orika.impl.generator.Specification>. It is not possible to send any sub-class (or implementation) since the expected type should be Specification.class. Changing it to "Class<T extends ma.glasnost.orika.impl.generator.Specification>" will make it possible to pass the specification class that one wishes to replace.

**Comment by kalyan01** [comment]
Some CI tests are failing for this PR, but the same tests have been failing across several other PR's. Are all these PR's blocked from merging? This is my first contribution, trying to understand the process around submitting and merging PR's.

**Comment by andreabertagnolli** [comment]
The CI now is green :)
