### ISSUE TITLE
Orika does not exclude fields when using allargs constructor

### ISSUE THREAD

**Issue by zhukboh** [orika-mapper/orika#135]
Model:

``` javascript
class Foo {
    private String a;
    private String b;
    private String c;

    public void setA(String a) {
        this.a = a;
    }

    public void setB(String b) {
        this.b = b;
    }

    public void setC(String c) {
        this.c = c;
    }
}

class FooDto{
    private String a;
    private String b;
    private String c;

    public FooDto() {
    }

    public FooDto(String a, String b, String c) {
        this.a = a;
        this.b = b;
        this.c = c;
    }

    public void setA(String a) {
        this.a = a;
    }

    public void setB(String b) {
        this.b = b;
    }

    public void setC(String c) {
        this.c = c;
    }
}
```

Mapper configuring 

``` javascript
class Mapper extends ConfigurableMapper {
    @Override
    protected void configure(final MapperFactory factory) {
        factory.classMap(Foo.class, FooDto.class)
                .exclude("a")
                .exclude("c")
                .byDefault()
                .register();
    }
}
```

In this case when mapping _Foo_ to _FooDto_ _public FooDto(String a, String b, String c)_ constructor was used to instantiate _FooDto_ and all fields of this object were also instantiated with values from _Foo_ object. Then later only _FooDto.setB()_ was uses as expected to map proper field. As an outcome we obtain an object of _FooDto_ class with all fields mapped, but it was expected to map _foo.b -> fooDto.b_ only. and _fooDto.a_ and _fooDto.c_ to be nulls(or instantiated by default values from _FooDto_). I could not find any documentation on this behavior so I think it is a bug.

**Comment by andreabertagnolli** [comment]
By default orika tries to match the constructor with the same number/type/name of parameters that it should map.

To make it use the default constructor you can add to the classMap `.constructorB(), so the constructor with zero arguments it will be used.

For me it's not a bug ;)
