### ISSUE TITLE
Cannot instantiate the type CustomMapper

### ISSUE THREAD

**Issue by edelsbrunner** [orika-mapper/orika#138]
Hi.

I want to map abstract nested property's fields. 

My idea was to make something like this: 

```
.customize(new CustomMapper<> {
    void mapBToA(Destination destination, Source source) {
   if(source.fieldB instanceof NestedType) {
      destination.fieldA2 = ((NestedType)source.fieldB).nestedField2;
   }
 }});
```

I'm using version 1.4.5, but is not possible to register a CustomMapper like described in the documentation I get a: 

```
Cannot instantiate the type CustomMapper<SourceA,DestinationB>
```

Can someone explain me how to use the customize method in version 1.4.5?

Best Regards.

Marius

**Comment by mariuserik** [comment]
I changed my version to 1.4.3 and was able to do it.

**Comment by andreabertagnolli** [comment]
In 1.4.6 you have to set explicit target arguments into <> and the method signature of mapBtoA is:
`mapBtoA (B b, A a, MappingContext context)`
