### ISSUE TITLE
Some objects are getting duplicated when using BidirectionalConverter

### ISSUE THREAD

**Issue by olkow** [orika-mapper/orika#162]
I have a class hierarchy like this one:
A
-B
--C
-C
A.B.C is the same object instance as A.C

I have a default MapperFactory for the class A and BidirectionalConverter<B,B'> registered in ConverterFactory. The BidirectionalConverter<B,B'> delegates creation of C' to mapperFacade.

The result is:
A'
-B'
--C1'
-C2'

The problem is the A'.B'.C1' is not the same object instance as A'.C2'. Is it a defect or am I'm doing something wrong? I believe that the invocation context with the HashMap of objects already mapped is lost somewhere in the process. I'll provide a failing testcase later in the afternoon.

**Comment by brabenetz** [comment]
I'm working on a patch (see #117 https://github.com/orika-mapper/orika/files/611345/orika-2016-11-08.txt ).

**Comment by olkow** [comment]
I can see at master that the interface of public abstract class BidirectionalConverter<S, D> has changed. Both convertFrom and convertTo methods have one additional parameter: MappingContext. That's exactly what I need. Looking forward to see the 1.5.0 release.

**Comment by andreabertagnolli** [comment]
Will be fixed on 1.5.0
