### ISSUE TITLE
DefaultMapperFactory.classMap got in infinity loop when using F-bounded polymorphism

### ISSUE THREAD

**Issue by chanjarster** [orika-mapper/orika#167]
DefaultMapperFactory.classMap got in infinity loop when using [F-bounded polymorphism](https://en.wikipedia.org/wiki/Bounded_quantification#F-bounded_quantification). 

Inifnity loop happens in ``ma.glasnost.orika.property.PropertyResolver#resolveGenericType``

Below is the test case:

```java
interface BaseInterface<R extends BaseInterface<R>> {
// interface BaseInterface<R> can also cause the problem
}

interface ChildInterface extends BaseInterface<ChildInterface> {
  Set<Foo> getSet();
}

class Foo {
}
```

```java
DefaultMapperFactory mapperFactory = new DefaultMapperFactory.Builder().build();
mapperFactory.classMap(ChildInterface.class, ChildInterface.class)
    .byDefault()
    .register();
```

**Comment by andreabertagnolli** [comment]
I think it's the same of #166

**Comment by brabenetz** [comment]
That this is a duplicate, was my first thinking too.
But the inifinity loop also occurs if the base Interface is a "normal" generics: like
interface BaseInterface<R> {}
I think it has something to do with https://github.com/orika-mapper/orika/commit/9dd83e023ed0949e0ac71bcae07df7ba8cbaf6e2

**Comment by chanjarster** [comment]
@andreabertagnolli I don't think this is same of #116 . No StackOverflowException occured. The infinity loop happens at [PropertyResolver.java#L183](https://github.com/orika-mapper/orika/blob/master/core/src/main/java/ma/glasnost/orika/property/PropertyResolver.java#L182).

At that line, ``referenceInterface = reference.findInterface(TypeFactory.valueOf(owningType));`` ``referenceInterface``got the result same as ``reference``, and following iteration just got the same result again and agian.

And I agree with @brabenetz , these codes add on 9dd83e0

**Comment by brabenetz** [comment]
I think this changes fixes the bug (at least all tests runs green).
but I'm not 100% sure if I understand the code right (generics are complicated....)
[Uploading ISSUE-167_infinity_loop.zip…]()

**Comment by chanjarster** [comment]
@brabenetz Thank you, I think that works
