### ISSUE TITLE
Support for JSR-310 (Date and Time)

### ISSUE THREAD

**Issue by akihyro** [orika-mapper/orika#170]
Are there plans to support JSR-310 (`java.time.LocalDate`, `java.time.LocalDateTime`, `java.time.LocalTime`, etc)?

Currently (version 1.5.0), needs to register converters.
For example:

```java
mapperFactory.getConverterFactory()
        .registerConverter(new PassThroughConverter(LocalDate.class));
```

I will be happy, if it conversion becomes built-in.

Thanks.

**Comment by andreabertagnolli** [comment]
For sure this is an interesting one :)

Just for start a discussion, this is a list of the types relatives to this specification I found, I'm not sure the list is complete, but maybe someone can help :)

- `Instant`
- `Duration`
- `LocalDate`
- `LocalTime`
- `LocalDateTime`
- `ZonedDateTime`
- `DayOfWeek`
- `Month`
- `MonthDay`
- `OffsetDateTime`
- `OffsetTime`
- `Period`
- `Year`
- `YearMonth`
- `ZonedDateTime`
- `ZoneOffset`

**Comment by chanjarster** [comment]
I think all classes implements ``TemporalAccessor`` are all immutable.

http://www.oracle.com/technetwork/articles/java/jf14-date-time-2125367.html


> Core Ideas
> The new API is driven by three core ideas: 
> 
> Immutable-value classes. One of the serious weaknesses of the existing formatters in Java is that they aren’t thread-safe. This puts the burden on developers to use them in a thread-safe manner and to think about concurrency problems in their day-to-day development of date-handling code. The new API avoids this issue by ensuring that all its core classes are immutable and represent well-defined values.

**Comment by nathansgreen** [comment]
@chanjarster On top of `TemporalAccessor` you also need at least `TemporalAmount` and possibly `TemporalUnit`.

**Comment by brabenetz** [comment]
Have someone already started with this?
Otherwise, I think I could do that.

**Comment by brabenetz** [comment]
I added following classes:

TemporalAccessor:
 * java.time.Instant
 * java.time.LocalDate
 * java.time.LocalDateTime
 * java.time.LocalTime
 * java.time.MonthDay
 * java.time.OffsetDateTime
 * java.time.OffsetTime
 * java.time.Year
 * java.time.YearMonth
 * java.time.ZoneOffset
 * java.time.ZonedDateTime
 * java.time.chrono.HijrahDate
 * java.time.chrono.JapaneseDate
 * java.time.chrono.JapaneseEra
 * java.time.chrono.MinguoDate
 * java.time.chrono.ThaiBuddhistDate

TemporalAmount:
 * java.time.Duration
 * java.time.Period

DayOfWeek and Month are enums and already handled as immutable.

**Comment by nathansgreen** [comment]
`TemporalUnit` is an interface whose  implementations are required to be
immutable. I think whatever changes you make should account for that.

**Comment by brabenetz** [comment]
TemporalUnit has only two implementations (ChronoUnit, Unit) which both are enums.
Enums are already handled as immutable (CopyByRef if sourceType == destinationType).

**Comment by nathansgreen** [comment]
That's true of the built in implementations, but may not be true of third
party libraries or future releases of Java.

**Comment by dostiharise** [comment]
I am facing error mapping java.util.Currency.
