### ISSUE TITLE
NullPointerException when map an element to a list

### ISSUE THREAD

**Issue by andreabertagnolli** [orika-mapper/orika#175]
Maybe I missing the correct use, but I want to map a single value in every object inside a list.

Here's the failing test case:
`
     public void maps_one_value_to_all_elements_in_collection() {
        DefaultMapperFactory mapper = new DefaultMapperFactory.Builder().build();

        mapper.classMap(Source.class, Destination.class)
                .field("nested", "nested")
                .field("value", "nested{value}")
                .byDefault()
                .register();

        Source source = new Source();
        source.setValue("some data");
        source.setNested(Arrays.asList(aNestedSource("one"), aNestedSource("two")));

        Destination destination = mapper.getMapperFacade().map(source, Destination.class);

        assertEquals("some data", destination.getNested().get(0).getValue());
        assertEquals("some data", destination.getNested().get(1).getValue());
    }

    private NestedSource aNestedSource(String id) {
        NestedSource nested = new NestedSource();
        nested.setId(id);
        return nested;
    }

    public static class Source {

        private String value;
        private List<NestedSource> nested = new ArrayList();

        public void setValue(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        public void setNested(List<NestedSource> nested) {
            this.nested = nested;
        }

        public List<NestedSource> getNested() {
            return nested;
        }
    }

    public static class Destination {

        private List<NestedDestination> nested;

        public List<NestedDestination> getNested() {
            return nested;
        }

        public void setNested(List<NestedDestination> nested) {
            this.nested = nested;
        }
    }

    public static class NestedSource {

        private String id;

        public void setId(String id) {
            this.id = id;
        }

        public String getId() {
            return id;
        }
    }

    public static class NestedDestination {
        private String id;
        private String value;

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public String getValue() {
            return value;
        }

        public void setValue(String value) {
            this.value = value;
        }
    }
`

I'll look at the code by myself, but any help appreciated :)

**Comment by brabenetz** [comment]
Could be the same as #104
I'm not sure if a single property to collection mapping and visa-versa is part of the feature-set of Orika.
You can always use a CustomMapper for such special cases.
On the other hand, #104 is also marked as Bug...

**Comment by andreabertagnolli** [comment]
I tried the inverse case (map Destination to Source) and I correctly see the Source.value field setted with the value of the last NestedDestination in the list, so I think this is a bug :)

I'm looking, but today seems that the debugger won't let me watch into generated mapper! :rage:

**Comment by andreabertagnolli** [comment]
ok, I found the problem. I noticed that the MultiOccurrenceToMultiOccurrence specification was iterating over src nodes only, I make it iterating over dest nodes too and the problem is still resolved.
Had to explicitly define the `nested-nested`, otherwise it didn't work, dunno why but i'm investigating...

`mapper.classMap(Source.class, Destination.class)
                .field("nested", "nested")
                .field("value", "nested{value}")
                .byDefault()
                .register();`

will open the pull request soon :)

**Comment by brabenetz** [comment]
Great Work!
Can you please review my comment on #104?
I think #104 can be closed after that.
