### ISSUE TITLE
Support for mapping one type to many

### ISSUE THREAD

**Issue by udalrich** [orika-mapper/orika#176]
I have a class `A`

    class A {
       public String getType();
       public int getX()
    }

that I want to map to multiple types `B1`, `B2`, ...

    class B1 {
        public int x();
    class B2  {
        public int theX();
    }

based on `getType`.  Defining a mapping from `Bn` to `A` is easy, as I can just define a single-direction map from `Bn` to `A`.  There does not seem to be a good way to define the mapping from `A` to `Bn`.

The `Bn` are built with a builder, so I am currently defining the mapping by 

    mapperFactory.classMap(B1.class, A.class).
      map("x", "x").
      register();

    mapperFactory.getConverterFactory().registerConverter(new CustomConverter<A, B1>() {
      public B1 convert(A a, Type<? extends B1> type) {
        return B1.builder().x(x.getX()).build();
      }
    });

Can I define multiple converters from `A` to `Bn` and the convert it by manually checking?  Is there a more automated way?

    if (a.getType().equals("1")) return mapperFacade.convert(a, B1.class);
    if (a.getType().equals("2")) return mapperFacade.convert(a, B2.class);

It would be good if I could write make `Bn` extend `B`, and then with the same mapping definitions as above, have `mapperFacade.convert(a, B.class)` return either a B1 or a B2 based on the `a.getType()`.

**Comment by brabenetz** [comment]
I would have thought using an ObjectFactory would be the right way for this:
```java
final MapperFactory factory = new DefaultMapperFactory.Builder().build();

factory.registerObjectFactory(new ObjectFactory<B>() {
    public B create(Object source, MappingContext mappingContext) {
        A a = (A) source;
        final B b;
        if (a.getType().equals("1")) {
            b = new B1();
        } else if (a.getType().equals("2")) {
            b = new B2();
        } else {
            throw new IllegalArgumentException("type not supported: " + a.getType());
        }
        return b;
    }
    
}, TypeFactory.valueOf(B.class), TypeFactory.valueOf(A.class));

factory.classMap(A.class, B1.class)
        .field("x", "x1")
        .byDefault()
        .register();

factory.classMap(A.class, B2.class)
        .field("x", "x2")
        .byDefault()
        .register();

B b = factory.getMapperFacade().map(a, B.class);
```
But it' doesn't work (At least in the current version). Maybe a Bug!?

I only found a Workaround by using a complete CustomConverter:

```java
final MapperFactory factory = new DefaultMapperFactory.Builder().build();

factory.getConverterFactory().registerConverter(new CustomConverter<A, B>() {
    
    public B convert(A a, Type<? extends B> destinationType, MappingContext mappingContext) {
        B cachedObject = mappingContext.getMappedObject(a, destinationType);
        if (cachedObject != null) {
            return cachedObject;
        }
        final B b;
        if (a.getType().equals("1")) {
            b = new B1();
        } else if (a.getType().equals("2")) {
            b = new B2();
        } else {
            throw new IllegalArgumentException("type not supported: " + a.getType());
        }
        
        mappingContext.cacheMappedObject(a, (Type) destinationType, b);
        
        mappingContext.beginMapping(sourceType, a, destinationType, b);
        try {
            factory.getMapperFacade().map(a, b, mappingContext);
        } finally {
            mappingContext.endMapping();
        }
        
        return b;
    }
    
});
factory.classMap(A.class, B1.class)
        .field("x", "x1")
        .byDefault()
        .register();

factory.classMap(A.class, B2.class)
        .field("x", "x2")
        .byDefault()
        .register();

B b = factory.getMapperFacade().map(a, B.class);
```

Here are the full TestCase I Used:
[Issue176TestCase.java.txt](https://github.com/orika-mapper/orika/files/670641/Issue176TestCase.java.txt)

**Comment by brabenetz** [comment]
I think I can implement this.

The Problem is, that during generating phase no single mapper can be used because the `ObjectFactory` decides during Mapping which instance will be created.

I will introduce a `MultipleMapperWrapper` which contains all possible mappers.
This `MultipleMapperWrapper` can than decide during Mapping (dependent of the created Object from The `ObjectFactory`) which concrete Mapper should be used.

Because of the (small) performance penalty this `MultipleMapperWrapper` will only be used if a custom `ObjectFactory` is involved.
