### ISSUE TITLE
Roadmap for 1.5.1?

### ISSUE THREAD

**Issue by 123Haynes** [orika-mapper/orika#202]
Hi,

I'm just wondering what still needs to be done for a 1.5.1 release. 
There isn't a milestone for it and I think the java 8 time API changes alone would already warrant a new release.  
Anything I can do to help to get a new release out?

regards,
Hannes

**Comment by 123Haynes** [comment]
@elaatifi can you voice your opinion on this please? :smile:  
I'm willing to help with whatever is needed.

**Comment by elaatifi** [comment]
Hi !
Sorry for the late reply I'm on it  :smile:

**Comment by 123Haynes** [comment]
@elaatifi awesome :+1:   Let me know if you need help with anything :smile:

**Comment by brabenetz** [comment]
I prepared the release-notes:
https://github.com/orika-mapper/orika/wiki/Release-notes-1.5.1
Please review.

**Comment by 123Haynes** [comment]
looks good to me :+1:

**Comment by andreabertagnolli** [comment]
Super!

**Comment by elaatifi** [comment]
It is out.

**Comment by 123Haynes** [comment]
@elaatifi awesome :+1:
