### ISSUE TITLE
How to map single attribute of src Object to an attribut of each object of a list of destination object

### ISSUE THREAD

**Issue by rupat** [orika-mapper/orika#214]
class ObjectSrc {
public String attribut1;
}
class ObjectDst {
public List<ObjectX> objectXList;
}

class ObjectX {
public String attribut2;
}

MapperFactory mapperFactory = new DefaultMapperFactory.Builder().build();
// here i have to set "objectXList[0].attribut2" or so, but
// first this mapping dont work (objectDst.attribut2 is not set after mapping)
// second thing is how to set for every item of objectXList the attribut attribut2 to attribut 1 of objectSrc.
mapperFactory.classMap(ObjectSrc.class, ObjectDst.class)
				.field("attribut1", "objectXList[].attribut2")
				.byDefault()
				.register();
MapperFacade mapperFacade = mapperFactory.getMapperFacade();
mapperFacade.map(objectSrc, objectDst);

Maybe someone can help me ?

**Comment by rupat** [comment]
no comment, can i provide some informations for finding a solution ? any questions ?

Please help !

**Comment by stapetro** [comment]
Please provide a complete unit test. The code above doesn't fully describe the issue. At least I can't understand it.

**Comment by rupat** [comment]
Have written a little maven test project for showing my problem. Would be great if you take a look at it. Thx

[orikaattr2list.zip](https://github.com/orika-mapper/orika/files/1073812/orikaattr2list.zip)

**Comment by stapetro** [comment]
I share the code below to be easily visible:

```java
public class ContractData {
	public String contractnumber;
	public String someValue;
}
public class Contract {
	public List<SubContract> subcontracts;
	public String someValue;
}
public class SubContract {
	public String attribut2;
}

public class MainTest {
	@Test
	public void mapTest() throws Exception {
		ContractData contractData = new ContractData();
		contractData.contractnumber = "123";
		contractData.someValue = "456";

		Contract contract = new Contract();
		SubContract subContract1 = new SubContract();
		SubContract subContract2 = new SubContract();
		contract.subcontracts = Arrays.asList(subContract1, subContract2);

		MapperFactory mapperFactory = new DefaultMapperFactory.Builder().build();
		mapperFactory.classMap(ContractData.class, Contract.class)
				// how to declare the mapping here ?
				.field("contractnumber", "subcontracts{attribut2}")
				.byDefault()
				.register();
		MapperFacade mapperFacade = mapperFactory.getMapperFacade();
		mapperFacade.map(contractData, contract);

		Assert.assertEquals(contractData.someValue, contract.someValue);
		Assert.assertEquals(contractData.contractnumber, contract.subcontracts.get(0).attribut2);
		Assert.assertEquals(contractData.contractnumber, contract.subcontracts.get(1).attribut2);

	}
}
```
Here's a zip with the fixed unit test.
[orikaattr2list_fix.zip](https://github.com/orika-mapper/orika/files/1075584/orikaattr2list_fix.zip)

**Comment by rupat** [comment]
Ahhh, very good thanx !
