### ISSUE TITLE
How to exclude a property of a nested multi-occurance element.

### ISSUE THREAD

**Issue by medvednic** [orika-mapper/orika#222]
I have two classes: `A` and `B`.
A has a property `items` which is a collection of `B`, when mapping I would like to exclude the id property of `A` and of all `B` items. How can I achieve it? The closest thing I found in the user guide is the `names{fullName}` [example when working with nested multi-occurrence elements](https://orika-mapper.github.io/orika-docs/mappings-via-classmapbuilder.html) (nothing on exclusion though) - so I tried to do something similar to exclude the id of `B` but it results in the exclusion of the entire items property (needless to say that A's id gets excluded properly).

```
@Entity
public class A {

    @Id
    @GeneratedValue
    private Long id;
    //...

    @OneToMany()
    @JoinColumn(name = "a_id")
    private Set<B> items;

    // getters and setters
}

@Entity
public class B {

    @Id
    @GeneratedValue
    private Long id;
    //...

    public B() {}

    // getters and setters
}

MapperFactory mapperFactory = new DefaultMapperFactory.Builder().build();
        mapperFactory.classMap(A.class, A.class)
                .mapNulls(true)
                .exclude("id")
                .exclude("items{id}")
                .byDefault()
                .register();

MapperFacade mapperFacade = mapperFactory.getMapperFacade();
A dest = mapperFacade.map(source, A.class);
```

**Comment by elaatifi** [comment]
You can just put exclude on B.id
mapperFactory.classMap(B.class, B.class)
                .mapNulls(true)
                .exclude("id")
                .byDefault()
                .register();

**Comment by medvednic** [comment]
Yes, I"m aware of this but forgot to mention - I've got lots of sets of different classes inside `A` (about 15), only `B` is shown here for brevity.
I want to avoid lots of mappers, my goal is to define everything in the mapper of `A` to `A` - hence exclude is used.

**Comment by elaatifi** [comment]
So basically you want to exclude id everywhere ?
to do that you need to create a custom class map builder with a custom byDefault method.

https://gist.github.com/elaatifi/5212119

here is an example of how to create custom class map builders, for instance this one is supporting annotations, but you can provide your own rules : exclude id fields or any other generic rule.

**Comment by medvednic** [comment]
Thanks, I will look into it - but is there a way to explicitly exclude a property of a nested multi-occurrence element? `.exclude("items{id}")`?

**Comment by elaatifi** [comment]
Unfortunately there is no way to exclude nested elements

**Comment by medvednic** [comment]
Thanks.
I tried a workaround using an abstract class and a custom mapper, it seems to work.

**Comment by medvednic** [comment]
I've successfully achieved my goal using your suggestion to create a custom class map builder, it is much more convenient than my attempted workaround.
I will post Gist later this week.

**Comment by elaatifi** [comment]
Thanks for the update !

**Comment by medvednic** [comment]
Here is the [gist of the solution](https://gist.github.com/medvednic/93e83899a14c4a590b5217bd4a999cce), Custom `ClassMapBuilder` which excludes every filed that has `Id` annotation.
Additioanly, here is how to actually use a custom `ClassMapBuilder`:
```
  MapperFactory mapperFactory = new DefaultMapperFactory
            .Builder()
            .classMapBuilderFactory(new IdExclusionClassMapBuilder.Factory())
            .build();
```
