### ISSUE TITLE
map to map with filter cause NPE

### ISSUE THREAD

**Issue by michalkalisz** [orika-mapper/orika#232]
When source and destination class have map field and additionally custom filter is defined mapping will cause NPE:

Caused by: ma.glasnost.orika.MappingException: While attempting the following mapping:
sourceType = MapToMapWithFilterTest.FirstClassWithMap
sourceProperty = map(Map<String, String>)
destinationType = MapToMapWithFilterTest.SecondClassWithMap
destinationProperty = map(Map<String, String>)
Error occurred: java.lang.NullPointerException
	at ma.glasnost.orika.impl.generator.MapperGenerator.addMapMethod(MapperGenerator.java:177)
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:72)
	... 27 more
Caused by: java.lang.NullPointerException
	at ma.glasnost.orika.CustomFilter.appliesTo(CustomFilter.java:87)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.getFilter(SourceCodeContext.java:939)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.applyFilters(SourceCodeContext.java:815)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.mapFields(SourceCodeContext.java:762)
	at ma.glasnost.orika.impl.generator.specification.MapToMap.generateMappingCode(MapToMap.java:81)
	at ma.glasnost.orika.impl.generator.SourceCodeContext.mapFields(SourceCodeContext.java:768)
	at ma.glasnost.orika.impl.generator.MapperGenerator.generateFieldMapCode(MapperGenerator.java:251)
	at ma.glasnost.orika.impl.generator.MapperGenerator.addMapMethod(MapperGenerator.java:174)
	... 28 more

-----
[MapToMapWithFilterTest.txt](https://github.com/orika-mapper/orika/files/1257266/MapToMapWithFilterTest.txt)

**Comment by michalkalisz** [comment]
When code generator (ObjectFactoryGenerator or MapToMap) wants to do maping between source property to variable uses ma.glasnost.orika.impl.generator.SourceCodeContext#mapFields :
_MapToMap_
`code.mapFields(FieldMapBuilder.mapKeys(s.mapKeyType(), d.mapKeyType()), sourceKey, newKey, null, null),`
or 
_ObjectFactoryGenerator_
`out.append(code.mapFields(fieldMap, s, v, destinationType, logDetails));` 

mapFields method then call ma.glasnost.orika.impl.generator.SourceCodeContext#getFilter to indicate which filter should be applied:
`if (filter.appliesTo(sourceProperty.property(), destinationProperty.property())) {`
but destination doesn't have property reference! so it receive null as a second argument.

**Comment by andreabertagnolli** [comment]
can you report a failing unit test?

**Comment by michalkalisz** [comment]
Sure (it was attached as text file at first comment)
```java
import java.util.HashMap;
import java.util.Map;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import ma.glasnost.orika.MapperFactory;
import ma.glasnost.orika.NullFilter;
import ma.glasnost.orika.impl.DefaultMapperFactory;

public class MapToMapWithFilterTest {

    private MapperFactory mapperFactory;

    @Before public void setUp() throws Exception {
        mapperFactory = new DefaultMapperFactory.Builder().build();
        mapperFactory.registerFilter(new NullFilter<>());
        mapperFactory.classMap(FirstClassWithMap.class, SecondClassWithMap.class).byDefault().register();
    }

    @Test
    public void testMapToMapWithFilter() {
        FirstClassWithMap firstMap = new FirstClassWithMap();
        firstMap.setMap(new HashMap<>());
        firstMap.getMap().put("A", "1");

        SecondClassWithMap transformed = mapperFactory.getMapperFacade().map(firstMap, SecondClassWithMap.class);

        Assert.assertNotNull(transformed);
        Assert.assertNotNull(transformed.getMap());
        Assert.assertEquals("1", transformed.getMap().get("A"));
    }

    public static class FirstClassWithMap {

        private Map<String, String> map;

        public Map<String, String> getMap() {
            return map;
        }

        public void setMap(Map<String, String> map) {
            this.map = map;
        }
    }

    public static class SecondClassWithMap {

        private Map<String, String> map;

        public Map<String, String> getMap() {
            return map;
        }

        public void setMap(Map<String, String> map) {
            this.map = map;
        }
    }

}

```
