### ISSUE TITLE
Builtin Converter with defaultMapping not working

### ISSUE THREAD

**Issue by Shinryuken** [orika-mapper/orika#236]
Hi, i discovered this issue, i have a simple test, i'm not able to correctly convert the Date fields between the 2 entities, looks like that orika insists to keep a nested/field-by-field mapping on the 2 Date objects (Date and XMLGregorianCalendar), i tried to exclude the fields but the destination object keeps getting wrong values, it works only if you exclude the "byDefault()" mapping.

This should be done automatically using the Builtin converter without any additional configuration right?

Thanks in advance
```
package org.keep.service.mapping;

import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

import javax.xml.datatype.XMLGregorianCalendar;

import ma.glasnost.orika.MapperFactory;
import ma.glasnost.orika.impl.DefaultMapperFactory;
import ma.glasnost.orika.metadata.CaseInsensitiveClassMapBuilder;
import ma.glasnost.orika.metadata.ClassMap;
import ma.glasnost.orika.metadata.ClassMapBuilder;
import ma.glasnost.orika.metadata.FieldMap;


public class DateMappingTest {
    
    public static class Source {
        public String lastName;
        public Date currentage;
    }
    
    public static class Destination {
        public String lastname;
        public XMLGregorianCalendar currentAge;
        
		@Override
		public String toString() {
			return "Destination [lastname=" + lastname + ", currentAge=" + currentAge + "]";
		}
        
    }
    
    public static void main(String[] args) {
		new DateMappingTest().testFieldMapping();
	}
    
    
    public void testFieldMapping() {
        
        MapperFactory mapperFactory = new DefaultMapperFactory.Builder().classMapBuilderFactory(new CaseInsensitiveClassMapBuilder.Factory()).build();
        
        ClassMapBuilder<Source, Destination> cmBuilder = mapperFactory.classMap(Source.class, Destination.class)
        .exclude("currentage")
        .exclude("currentAge")
        .field("currentage", "currentAge")
        .byDefault()
        ;
        cmBuilder.register();

        printMapping(cmBuilder);
        
        Source source = new Source();
        source.currentage = Calendar.getInstance().getTime();
        source.lastName = "Rossi";
        
        Destination dest = mapperFactory.getMapperFacade().map(source, Destination.class);
        
        System.out.println(dest);
        
    }


	private void printMapping(ClassMapBuilder<Source, Destination> cmBuilder) {
        
        ClassMap<Source, Destination> map	=	cmBuilder.toClassMap();
 
        Map<String, String> mapping = new HashMap<String, String>();
        for (FieldMap f : map.getFieldsMapping()) {
            mapping.put(f.getSource().getExpression(), f.getDestination().getExpression());
        }
        
        for( Entry<String, String> entry : mapping.entrySet()) {
        	System.out.println(entry.getKey() + "->"+ entry.getValue());
        }
	}

    
}
```

**Comment by andreabertagnolli** [comment]
it seems that with the `CaseInsensitiveClassMapBuilder`, after converting the Date to XMLGregorianCalendar, it does some mappings between fields of the type Date.

Doing this, it pass through the _Deprecated_ method *getYear()* on Date, and its implementation is:
```return normalize().getYear() - 1900;```
So, the destination date will take the actual year minus 1900, so 117, and the mapping fails.

I advice you to remove that specific ClassMapBuilder unless do you need it, the code will work.
(you can also remove the "exclude" settings from the class map)

Dunno if it is a bug, there's no tests on this specific `CaseInsensitiveClassMapBuilder` that talks about its behavior.

I think that, just by reading the name of the class, the only difference between `CaseInsensitiveClassMapBuilder` and its superclass should be that the first one must map by default also the fields with same name but with different case.

**Comment by andreabertagnolli** [comment]
ok, `CaseInsensitiveClassMapBuilder` took all the properties, also the nested one, just because the `getPropertyExpression` at https://github.com/orika-mapper/orika/blob/master/core/src/main/java/ma/glasnost/orika/metadata/CaseInsensitiveClassMapBuilder.java#L75

Changing that method with `getPropertiesForTypeA` it works, but there's no tests on that class so there's the probability to break something.

Any other thoughts? Otherwise I will add a test case, commit it and open a pull request ;)

**Comment by andreabertagnolli** [comment]
it seems that with the `CaseInsensitiveClassMapBuilder`, after converting the Date to XMLGregorianCalendar, it does some mappings between fields of the types Date and XMLGregorianCalendar.

Doing this, it pass through the _@Deprecated_ method *getYear()* on Date, that's implemented as:
```return normalize().getYear() - 1900;```
So, the destination date will take the actual year minus 1900, so 117, and the mapping fails.

I advice you to remove that specific ClassMapBuilder unless do you need it, the code will work.
(you can also remove the "exclude" settings from the class map)

Anyhow I think it's a bug ;)
