### ISSUE TITLE
Change jdk compile version to 1.7

### ISSUE THREAD

**Issue by andreabertagnolli** [orika-mapper/orika#242]
I think it's time to upgrade the jdk compile version from 1.6 to 1.7, there's no travis build that tests it.

Any thoughts?

**Comment by 123Haynes** [comment]
@andreabertagnolli I changed that in my pull request. 😃

**Comment by 123Haynes** [comment]
@andreabertagnolli can this be closed? :)

**Comment by andreabertagnolli** [comment]
Sure :)

**Comment by 123Haynes** [comment]
wow that was fast :D
