### ISSUE TITLE
Gitter channel for Orika

### ISSUE THREAD

**Issue by rajcspsg** [orika-mapper/orika#269]
Hi,

I see we could have gitter channel for collaboration of orika stakeholders.
It is just a suggestion.

**Comment by stapetro** [comment]
I vote for a collaboration channel.

**Comment by elaatifi** [comment]
Done. [Gitter](https://gitter.im/orika-mapper/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by 123Haynes** [comment]
@elaatifi this can be closed right? 😄
