### ISSUE TITLE
NullPointerException under Java 11

### ISSUE THREAD

**Issue by GMillerVarian** [orika-mapper/orika#278]
When upgrading from Java 10 to Java 11, mappers fail with NullPointerException. Is there a workaround for this or do we need to wait for a new release that works with Java 11? If the latter, is there an estimated release date?

**Comment by muminc** [comment]
Last time I checked, trunk version of orika builds + runs it's unit tests sucessfully on Java 11 (thanks to update of javassist to version 3.23.1-GA)

**Comment by muminc** [comment]
+1, I would like new release of orika mapper.

**Comment by elaatifi** [comment]
1.5.4 is on maven central with latest fixes
