### ISSUE TITLE
Mapping String with Dashes to Enum

### ISSUE THREAD

**Issue by algotradersxyz** [orika-mapper/orika#284]
ma.glasnost.orika.MappingException: java.lang.IllegalArgumentException: No enum constant xyz.algotraders.algotrader.core.enums.InstrumentSegment.CDS-OPT

Enum     CDS_OPT("CDS-OPT"),
String Value CDS-OPT

**Comment by elaatifi** [comment]
The best option is to create a custom converter, we could add support this feature but can have performance penalty. Since the reasonable way to do it is to catch the exception and try with dashes replaced with underscore ...
