### ISSUE TITLE
PermGen OOM?

### ISSUE THREAD

**Issue by cholf** [orika-mapper/orika#286]
public void method(){
 MapperFactory mapperFactory = new DefaultMapperFactory.Builder().build();
}

If u do like this, it will lead to PermGen OOM;  I think ,it is a bug;

**Comment by elaatifi** [comment]
No, Orika should be used as singleton or few instances per JVM not on each request/invocation.

**Comment by cholf** [comment]
> No, Orika should be used as singleton or few instances per JVM not on each request/invocation.

You can control the code,can't  control the behavior, right?
