### ISSUE TITLE
Orika Best Practises

### ISSUE THREAD

**Issue by bfrisoni** [orika-mapper/orika#306]
From the performance tuning wiki page, I understand that it would best to do the follow ( https://orika-mapper.github.io/orika-docs/performance-tuning.html ) :
1. MapperFactory should be used as a singleton 
2. MapperFacade should be used as singleton
3. Type<?> should be cached.
4. Use BoundMapperFacade for 2 particular types to speed up performance even more.
What it doesn't state is if the BoundMapperFacade should be cached as well or if this is done internally by orika? If there is documentation stating this please point me in that direction.

Thanks!

**Comment by elaatifi** [comment]
`BoundMapperFacade` are cached within a `MapperFactory`.
Also only one `MapperFacade` is available per `MapperFactory`

**Comment by bfrisoni** [comment]
Thanks!!
