### ISSUE TITLE
orika Error "java.lang.IllegalArgumentException: 'request.params['cp']{}' is not a valid element property for Object" Map<String,List<String>> to Double

### ISSUE THREAD

**Issue by rajcspsg** [orika-mapper/orika#332]
I'm using orika to map value between different java beans. 

Definition of  [ObjectA](https://github.com/rajcspsg/orika-demo/blob/master/common/src/main/java/mapper/ObjectA.java) - 

        public class ObjectA {

            private Request request;
        }

Definition of [Request](https://github.com/rajcspsg/orika-demo/blob/master/common/src/main/java/mapper/Request.java) is - 

        public class Request {

            private String id;

            private Map<String, List<String>> params;
        }

Definition of [ObjectB](https://github.com/rajcspsg/orika-demo/blob/master/common/src/main/java/mapper/ObjectB.java) - 

        public class ObjectB {
            
            private Long reqId;

            private Double cp;

        }

I've omitted the setters and getters for brevity.

Below is the code that maps from objectA to ObjectB -

        Map<String,String> fieldMap = new HashMap<>();
        fieldMap.put("request.id","reqId");
        fieldMap.put("request.params['cp']{}", "cp");

        ObjectA a = new ObjectA();
        Request request = new Request();
        request.setId("123");
        a.setRequest(request);

        Map<String, List<String>> params = new HashMap<String, List<String>>();
        params.put("id", new ArrayList<String>(){{add("2");}});
        params.put("cp", new ArrayList<String>(){{add("0.51"); add("0.52"); add("0.53"); }});

        MappingContext.Factory mcf = new MappingContext.Factory();
        MapperFactory mapperFactory = new DefaultMapperFactory.Builder().mapNulls(false).mappingContextFactory(mcf).dumpStateOnException(false).build();
        ClassMapBuilder<ObjectA, ObjectB> impBuilder = mapperFactory.classMap(ObjectA.class, ObjectB.class);
        fieldMap.forEach((k,v) -> impBuilder.field(k,v));
        impBuilder.register();

        BoundMapperFacade<ObjectA, ObjectB> delegate = mapperFactory.getMapperFacade(ObjectA.class, ObjectB.class);

        ObjectB b = delegate.map(a);

 
The code is in github [here](https://github.com/rajcspsg/orika-demo/blob/master/orika-1.5/src/main/java/mapper/ObjectAToObjectBDemo.java).

When I run this program I'm getting below error - 

>  Exception in thread "main" java.lang.IllegalArgumentException: 'request.params['cp']{}' is not a valid element property for ObjectA
>          at ma.glasnost.orika.property.PropertyResolver.getElementProperty(PropertyResolver.java:566)
>          at ma.glasnost.orika.property.PropertyResolver.getProperty(PropertyResolver.java:682)
>          at ma.glasnost.orika.property.PropertyResolver.getProperty(PropertyResolver.java:638)
>          at ma.glasnost.orika.metadata.ClassMapBuilder.resolveProperty(ClassMapBuilder.java:873)
>          at ma.glasnost.orika.metadata.FieldMapBuilder.<init>(FieldMapBuilder.java:78)
>          at ma.glasnost.orika.metadata.FieldMapBuilder.<init>(FieldMapBuilder.java:61)
>          at ma.glasnost.orika.metadata.ClassMapBuilder.fieldMap(ClassMapBuilder.java:328)
>          at ma.glasnost.orika.metadata.ClassMapBuilder.fieldMap(ClassMapBuilder.java:311)
>          at ma.glasnost.orika.metadata.ClassMapBuilder.field(ClassMapBuilder.java:249)
>          at mapper.ObjectAToObjectBDemo.lambda$main$0(ObjectAToObjectBDemo.java:36)
>          at java.util.HashMap.forEach(HashMap.java:1289)
>          at mapper.ObjectAToObjectBDemo.main(ObjectAToObjectBDemo.java:36)

I want to map first element of the key in "cp" in map `params` of the request object `ObjectA` to  variable `cp` in `ObjectB`.

What is wrong with my mapping `fieldMap.put("request.params['cp']{}", "cp");` and How can I fix the same?
 
Note: I'm using orika version [1.5.4](https://github.com/rajcspsg/orika-demo/blob/master/orika-1.5/build.gradle.kts#L16).

I've asked the same question in stackoverflow [here](https://stackoverflow.com/questions/59238854/orika-error-java-lang-illegalargumentexception-r-pcp-is-not-a-valid-el)

**Comment by stapetro** [comment]
Hello, 
I fixed it with a few corrections:
```java
...
// fix 1
fieldMap.put("request.params['cp'][0]", "cp"); // instead of request.params['cp']{}
...
Map<String, List<String>> params = new HashMap<String, List<String>>();
...add params
// fix 2
request.setParams(params);
```
You can find the working fix [here](https://github.com/stapetro/orika/blob/issue332/tests/src/main/java/ma/glasnost/orika/test/TestIssue332.java). I might delete the branch in future after you confirm the fix is working on your side.

**Comment by rajcspsg** [comment]
@stapetro your solution is working. I will close this issue.
