### ISSUE TITLE
Possible to use abtract class as ConfigurableMapper.map destination class type?

### ISSUE THREAD

**Issue by lohisoftware** [orika-mapper/orika#344]
Is there "orika way" of supporting use case where ConfigurableMapper.map destination class is an abstract class? For example, implementing object factory that decides which concrete class to instantiate, or something like that? I could not get it working.

The work around is to find out ahead of time which concrete class we want to map to, and then pass that as destination class to map method.

**Comment by stapetro** [comment]
Please provide example so we understand exactly what you want to achieve.
