### ISSUE TITLE
Inject security check

### ISSUE THREAD

**Issue by bosyak** [orika-mapper/orika#55]
Hi,
I did mapping with Orika and it's working perfect, so I have next task.
I have two objects of same class and I need a copy values from one to other and make security check for  each. 
Like this: securityCheck(PropertyNameOrSomething prop, Object srcValue, Object dstValue) {...}
To make decision if mapping is allowed I need some propertyDescription and property values of both objects.

Please, can you advice where I can extend Orika to make this checking possible?

**Comment by elaatifi** [comment]
You can use the filter API, there is even a test case that you can look at
https://github.com/orika-mapper/orika/blob/master/tests/src/main/java/ma/glasnost/orika/test/filters/FilterTestCase.java#L75

**Comment by bosyak** [comment]
It's almost what I need but still not.
I need both source and destination values in single method.

Also I can't find how I can register filter only for certain mapping, not globally.

I'm voting for change Filter API :+1:  :)
The best for me it's pass filter during map (suppose I can mistaking), like this:
PersonDto map = mapper.map(persionDto, PersonDto.class, securityFilter);

Please close ticket if...

**Comment by elaatifi** [comment]
Ah sorry this is not how it's supposed to work shouldMap is called before we even get source/destination value
BTW Even if you registered globally you can constrain it, by overriding boolean appliesTo(Property,Property)

**Comment by bosyak** [comment]
Thanks.
