### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by sskrla** [orika-mapper/orika#57]
I want to use [Sourcegraph](https://sourcegraph.com) for orika code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/orika-mapper/orika. (It should only take 30 seconds.)

Thank you!

**Comment by elaatifi** [comment]
Done. You're welcome !

**Comment by sskrla** [comment]
Thanks!
