### ISSUE TITLE
Cannot register converters after MapperFacade has been initialized

### ISSUE THREAD

**Issue by boss94** [orika-mapper/orika#59]
Hi,

I am not able to register any converters after the initial configure() has taken placen, including ANY field level converter...
Whenever I try, I am getting the following error:
Cannot register converters after MapperFacade has been initialized

BR,
Mannan

**Comment by elaatifi** [comment]
Hello,

This is how it's supposed to work. Once the MaperFacade has been initialized no more configuration can be done (except class-maps but it's not recommended, and may disappear in the future also)

So be sure to pre-configure all mapping rules in the configuration time.

**Comment by boss94** [comment]
Ohh, thanks for the quick answer! But I was using Ken Blair's idea to instantiate all the custom converters and mappers on Spring applicationContext's initialization...and that doesn't work anymore!
And I am not able to add CustomConverters on a field level neither, getting the same error...

Is there a way to make Orika instantiate the mapperFacade after Spring's ApplicationContext has started?

**Comment by elaatifi** [comment]
In fact the implementation may miss something, the only problem I can see is that the default constructor is called first which do the initialization of `MapperFacade`, so the only thing you have to do is to add a constructor in which you call 
```java
super(false); // to delay the initialization
```

And change post bean initialization do the actual `MapperFacade` initialization, by changing the `setApplicationContext` method like this:
```java
@Override
public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
    addAllSpringBeans(applicationContext);
}
```

**Comment by boss94** [comment]
Thanks again for your time, 
I actually tried this earlier but the local mapperFactory is null...so the following line fails:
```java
	public void addConverter(final Converter<?, ?> converter) {
		factory.getConverterFactory().registerConverter(converter);
	}
```
because the `factory

**Comment by boss94** [comment]
First, thanks a lot for your time.
I can't see a change between your version of the `setApplicationContext()` method and mine! :(

So, I tried your solution (disabling the init from the constructor) : 
```java
	public OrikaBeanMapper() {
		super(false);         
	}
```
but I still had to initialize the local `factory` befiore setting the `mapperFacade`, and since both factory and facade are set in `configurableMapper.init()`...the only place to do this is still in the overridden `configure()` method where I don't have access to the `applicationContext`!

So I came up with the following solution, which works. Please share your toughts and/or a better/cleaner solution ;) :
```java
//referencing the ApplicationContext in the class
private ApplicationContext applicationContext;

	@Override
	public void setApplicationContext(final ApplicationContext applicationContext) throws BeansException {
		this.applicationContext = applicationContext;
		this.init();
	}

	@Override
	protected void configure(final MapperFactory factory) {
		this.factory = factory;
		addAllSpringBeans();
		addConverter(new PassThroughConverter(org.joda.time.DateTime.class));
	}

```

Thanks again for your help.

**Comment by elaatifi** [comment]
Yes! of course sorry I edited my previous comment.

**Comment by boss94** [comment]
Thanks :)
