### ISSUE TITLE
Orika does not create intermediate property when mapping lists

### ISSUE THREAD

**Issue by adammichalik** [orika-mapper/orika#64]
Orika 1.4.5

See this test: https://gist.github.com/adammichalik/76104c6360ee446606f1#file-orikaintermediateobjectwithlisttest-java

Mapping to nested property (`a.b.c`) works fine in Orika for single-valued properties even if the intermediate object (`b`) does not exist. However, if the property is multi-valued, then mapping to `a.b.c{}` fails with NPE on `b` in the generated mapper if `b` was not already initialized.

**Comment by elaatifi** [comment]
I thought that the recent release will fix it but it persist, I will take a look at ASAP.
Thanks !

**Comment by adammichalik** [comment]
I just double-checked with 1.4.6 (released on the day of my report) and it still persists.
Thanks for looking into it!

**Comment by kmittal123** [comment]
Hi,
Just wanted to check when this issue will be fixed, any ETA you have as we are potential financial player and planning to use Orika but this issue is major roadblock.
Rgds,
Kamal

**Comment by kmittal123** [comment]
Hi,
Can you please update when this issue will  be fixed?
Rgds,
Kamal

**Comment by andreabertagnolli** [comment]
@elaatifi I think we can close this now :)
