### ISSUE TITLE
orika default mapping breaks when registering classMap with only byDefault()

### ISSUE THREAD

**Issue by hohwille** [orika-mapper/orika#65]
In oasp.io we actually created a facade for bean mappers such as dozer, orika, or MapStruct to prevent coupling to an fixed implementation and the being bound to it. We started with Dozer but want to switch to Orika as default. However, we are facing a strange issue:
The default mapping of Orika works but we want to add a specific custom mapping. Doing so broke the default mapping and our test. I now discovered that already adding the classMap for my A/B mapping with `mapper.classMap(A.class, B.class).byDefault().register()` already breaks the defaults and prevents some fields from being mapped.

Here is our test-case on github if you want to have a look (the use-case is quite simple so I am surprised that orika already fails with this setup, but we might do something wrong):
https://github.com/oasp/oasp4j/blob/develop/oasp4j-modules/oasp4j-beanmapping/src/test/java/io/oasp/module/beanmapping/common/impl/BeanMapperImplOrikaTest.java

**Comment by hohwille** [comment]
Any updates? Is Orika buggy and dead?

**Comment by elaatifi** [comment]
It's not dead but time is a limited resource sorry if you're issue got ignored but you can also try the pull request, it's more helpful than the last comment :)

**Comment by sesslinger** [comment]
I finally figured out, why Orika refused to map all fields in our test-case. Per default Orika only maps the fields declared in the target class (`B.class`). Fields declared in a class, which is implementing or extending `B.class` are being ignored. In order to change this behaviour you need to add `favorExtension(true)`, e.g. `mapper.classMap(A.class, B.class).favorExtension(true).byDefault().register()`.

I am still trying to find out, why Orika refuses to use the custom mapper, when `PersistenceEntity.class` is used in our test-case.

**Comment by andreabertagnolli** [comment]
@hohwille the link is not available anymore.
the issue is still valid?

**Comment by jndietz** [comment]
I think this is still an issue.

```java
@Component
class MatrixAccountDataMapper {

    def configure(MapperFactory mapperFactory) {
        mapperFactory.classMap(MatrixAccountLookup.class, PlanTradeConfirm.class)
            .byDefault()
            .register()
    }
}
```

Exception thrown when calling `mapperFacade.map()`...

```
java.lang.IllegalAccessError: tried to access class sun.misc.Launcher$AppClassLoader from class sun.misc.Orika_AppClassLoader_AppClassLoader_Mapper37836166146992$4
```

**Comment by jndietz** [comment]
After removing `byDefault()` and adding in explicit `field()` methods/builders, it works as expected.

**Comment by jndietz** [comment]
Adding `exclude("metaClass")` and `byDefault()` works.  Was shown by a coworker, but not sure exactly why that fixes it.  I am mapping between two JPA entities in my example.
