### ISSUE TITLE
Orika in Felix (OSGi)

### ISSUE THREAD

**Issue by Sandared** [orika-mapper/orika#66]
Hi,

I tried to use Orika in my OSGi setup, but didn't get it to work.
I'm using Felix 5.0 and everytime I try to resolve the dependencies for my small setup it complains about missing the package com.sun.jdi, which is used by javaassist, which is used by orika.

Has anyone tried to setup Orika in an OSGi Environment yet, and was successful in doing so?

Any advice is highly appreciated ;)

Best regards,
Thomas

**Comment by elaatifi** [comment]
Hi Thomas,

I didn't tried to use or test Orika in OSGi environment yet, but some people have done this before 
You can look at this example https://github.com/mekhanikov/orika-osgi
Kindest regards

**Comment by Sandared** [comment]
Hi Sidi,

nevermind :)
I've found a working solution from amdatu:
https://amdatu.atlassian.net/wiki/display/AMDATUDEV/Amdatu+ObjectMapper

It's using an older version of Orika, but is sufficient for my purposes :)

Best regards,
Thomas


2015-06-22 11:43 GMT+02:00 Sidi Mohamed EL AATIFI <notifications@github.com>
:

**Comment by elaatifi** [comment]
Thank you Thomas :)  Good to know !
