### ISSUE TITLE
CustomMapper ArrayIndexOutOfBoundsException if an intermediate generic superclass is used for a mapper implementation

### ISSUE THREAD

**Issue by adammichalik** [orika-mapper/orika#69]
Orika 1.4.6

I have a following class hierarchy:

```java
class GenericSuperMapper<S> extends CustomMapper<S, MyTarget> {...}
class ConcreteMapper extends GenericSuperMapper<MySource> {...}
```

I get

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at ma.glasnost.orika.CustomMapper.<init>(CustomMapper.java:45)
```

I would suggest in the `CustomMapper` constructor not to look at the direct superclass of `this`, but to look up the class hierarchy for the `CustomMapper` class and use the `getActualTypeArguments()` of that.

**Comment by elaatifi** [comment]
Thanks Adam !

**Comment by elaatifi** [comment]
Forget to mention that you can fix them manually (aType,bType) in the subclass constructor as a workaround

**Comment by adammichalik** [comment]
Unfortunately I don't think it's possible in that particular case. Since `CustomMapper` constructor has:

```
public CustomMapper() {
        java.lang.reflect.Type genericSuperclass = getClass().getGenericSuperclass();
        if (genericSuperclass != null && genericSuperclass instanceof ParameterizedType) {
            ParameterizedType superType = (ParameterizedType)getClass().getGenericSuperclass();
            try {
                aType = TypeFactory.valueOf(superType.getActualTypeArguments()[0]);
                bType = TypeFactory.valueOf(superType.getActualTypeArguments()[1]);
            } catch (IllegalArgumentException e) {
                /* do nothing; this was not extended by a user 
                 * getXXType methods must be manually overridden 
                 */
            }
        }
    }
```

You can see that (referring to my example) if I construct `ConcreteMapper` its constructor has to call a constructor of `GenericSuperMapper` and this in turn calls the constructor of Orika's `CustomMapper`. 

There in `CustomMapper` constructor, `this` is `ConcreteMapper`, so `genericSuperclass` becomes the `GenericSuperMapper` generic type, which is still an instance of `ParameterizedType`. So `superType` is also equal to the `GenericSuperMapper` generic type (we could just cast `genericSuperclass` instead of calling `getClass().getGenericSuperclass()` again btw.).

But `GenericSuperMapper` itself has only one type parameter, so the line
```
 bType = TypeFactory.valueOf(superType.getActualTypeArguments()[1]);
```
fails with `ArrayIndexOutOfBoundsException`. The try/catch block catches only `IllegalArgumentException`, so the `ArrayIndexOutOfBoundsException` bubbles uncaught, thus failing the whole constructor of the mapper without an option to adjust the A/B types manually.

**Comment by elaatifi** [comment]
I just pushed a fix,  can you please confirm if it fix your issue I also added a [quick test](https://github.com/orika-mapper/orika/blob/8d0f7837c703bc2853b557eb7cc74b06deb4cf38/tests/src/main/java/ma/glasnost/orika/test/custommapper/CustomMappingTestCase.java).

**Comment by adammichalik** [comment]
I checked 1.4.7-SNAPSHOT and it works fine with your fix. Thanks!
