### ISSUE TITLE
CustomConverter does not support parameterized types on subclasses

### ISSUE THREAD

**Issue by vtatai** [orika-mapper/orika#78]
I have the following custom converter:

```java
public class EntityToStringIdConverter<T extends BaseEntity<Long>> extends CustomConverter<T, String> {
...
}
```
Note that `BaseEntity` is a parameterized interface I have in my application.

I then register this converter as a custom converter, but it does not convert my fields. I have found out that the issue is that the `CustomConverter` code incorrectly detects the type `T` to be of type `BaseEntity`, and when it tries to match the type in the `canConvert` method it won't match for my concrete subclass (which implements `BaseEntity`).

The biggest problem is that I cannot customize the behavior of the `CustomConverter` class, since the `sourceType` field is final and set in the constructor. I was planning on simply passing along the actual class object for the concrete class, and set it in the `sourceType`. Is there a work around for this?

**Comment by elaatifi** [comment]
You can implement the Converter interface directly and put whatever condition you want in canConvert method

**Comment by vtatai** [comment]
Yes that's what I ended up doing. But perhaps the fields `sourceType` and `destinationType` could be marked as non-final? This would enable subclasses to tweak them.

**Comment by vtatai** [comment]
Actually, scratch that, I can see that on master this is already done. Thanks!
