### ISSUE TITLE
TypeFactory doesn't resolve the real Type Argument for parameterized type.

### ISSUE THREAD

**Issue by Fneuch** [orika-mapper/orika#83]
Given the following class hierarchy:
```java
public class Parent<T> {
	private T content;
	public T getContent() { return content; }
	public void setContent(T content) {	this.content = content; }
}

public static class Child extends Parent<Map<String, Element>> {	}
```
When using ```IntrospectorPropertyResolver``` to resolve the property "content" on child, we got a ```StackOverflowError```.

The problem came from ```TypeUtil#resolveActualTypeArguments```.  That validate the ```typeArguments``` only with ```Class```, it should validate ```ParametizedType``` too. 
To support that, line 79 should be : 
```Java
  if (typeArg instanceof ParameterizedType || typeArg instanceof Class) {
```

We create a branch to validate that and test it, want me to create a pull request with it?

**Comment by akley** [comment]
Hi guys,
I have the same problem as Fneuch while resolving following construct by IntrospectorPropertyResolver:

public class Child extends HashMap<Parent<?>, Object>{  }
public abstract class Parent<T> {  }

I use Orika 1.4.5

**Comment by elaatifi** [comment]
Can you verify on 1.5.0-beta1 ?

**Comment by akley** [comment]
in 1.5.0-beta0 the line is already not fixed
in 1.5.0-beta1 (I hope this is master) the line is already not fixed

The verification on 1.5.0-beta1 is much more complex under OSGi environment, so please give me some time. 
For now the fix from Fneuch works fine in my fork (based on 1.4.5)

Cheers,
Alex

**Comment by elaatifi** [comment]
I did not found the pull request can you please try again ?
