### ISSUE TITLE
Exclude() is not working as expected.

### ISSUE THREAD

**Issue by NicksMehta** [orika-mapper/orika#95]
Hi! there,

I am using Orika 1.4.6 and Hibernate 4. I want to exclude a property from mapping. I used `exclude()` but its not working as expected. 

**Whats happening**: when I make a field to exclude (instead of ignoring), it sets the target hibernate entitys' property to null (I think because its setting the source bean property to null instead of ignoring it). This will in turn sets the field to **NULL** in the database while saving that entity.

Heres the conceptual class diagram:

![orikatestdiagram](https://cloud.githubusercontent.com/assets/3250285/11766508/11b349c6-a1b1-11e5-86fa-7acf48f126b0.png)

I am using using the following configuration:

`new DefaultMapperFactory.Builder().compilerStrategy(new JavassistCompilerStrategy()).unenhanceStrategy(new HibernateUnenhanceStrategy()).build()`

Any suggestion will be appreciated!

If you want more information please let me know,  and I can post an example if needed.

Thanks,
Nikhil

**Comment by elaatifi** [comment]
When a field mapping is marked as excluded is (it got just ignored)
https://github.com/orika-mapper/orika/blob/1e5738994c14b0ebd72e67a8dc2622dd96f73764/core/src/main/java/ma/glasnost/orika/impl/generator/MapperGenerator.java#L143
